kobaltedev/kobalte

apps/docs/src/routes/docs/components/tabs.mdx

change 'seleceted' to 'selected'

docs: fix a little typo in Tabs data-attributes

---

apps/vanilla-extract-playground/index.html
apps/vanilla-extract-playground/package.json
apps/vanilla-extract-playground/src/App.tsx
apps/vanilla-extract-playground/src/index.css
apps/vanilla-extract-playground/src/index.tsx
apps/vanilla-extract-playground/src/styles.css.ts
apps/vanilla-extract-playground/tsconfig.json
apps/vanilla-extract-playground/vite.config.ts
packages/vanilla-extract/README.md
packages/vanilla-extract/package.json
packages/vanilla-extract/src/index.ts
packages/vanilla-extract/tsconfig.json
packages/vanilla-extract/tsup.config.ts
pnpm-lock.yaml

Not sure about your intention to have a dedicated package for having utils for vanilla extract but i'm working on an internal project with kobalte and this could be useful to others too 👀 
This pr introduces a new package `@kobalte/vanilla-extract` that may exports some utils for vanilla-extract, just like the tailwind ones.
Currently I've added a `componentStateStyles` method that allows to compose the style for kobalte data-attributes selectors. This allows to write the selectors through a configuration object which has the vanilla-extract type constraints, instead of writing it from scratch (eg. &:not([data-hover]) or [data-theme=dark] &:[data-hover]))
Example
```ts
// Vanilla
const btn = style({
selectors: {
"&[data-hover]": {
// styles
},
"&:not([data-active])": {
// styles
}, …
```

feat: vanilla-extract utils

---

apps/docs/src/routes/docs/core/components/dialog.mdx
apps/docs/src/routes/docs/core/components/popover.mdx

Adds missing `return (...)` statement in the example code of https://kobalte.dev/docs/core/components/popover#example and https://kobalte.dev/docs/core/components/dialog#example

docs: wrap examples with return

---

packages/core/package.json
packages/utils/package.json
packages/vanilla-extract/package.json

Defines `types` in the exports map, so that imports work when leveraging the newer `moduleResolution` tsconfig values (nodenext, node16, bundler).
More info: https://github.com/microsoft/TypeScript/issues/52363
Note that some of the example PRs linked to from the TS issue above are adding `types` to each specific condition inside of exports. In my experiments just adding `types` to the root of the exports map resolved the issues 🤷‍♂️.
Before (after, types work as expected):

fix: nexgen ts module resolutions

---

.changeset/thin-gorillas-relate.md
packages/tailwindcss/src/index.ts

Tailwind colors not available when using kobalte ui color palettes.

fix(tailwind): Tailwind colors not available

---

packages/core/src/combobox/combobox-base.tsx

Fixes #272 
Main issue was the use of ``filter`` on ``local.options`` which was returning the original array of options rather than actually filtering them out. 
Switching to a ``map`` or ``for..of`` loop was the solution. I opted for the ``for..of`` solution to avoid having the filter for undefined values afterwards.

fix(combobox): filtering of option groups

---

apps/docs/src/examples/skeleton.module.css
apps/docs/src/examples/skeleton.tsx
apps/docs/src/routes/docs/core.tsx
apps/docs/src/routes/docs/core/components/skeleton.mdx
packages/core/src/index.tsx
packages/core/src/skeleton/index.tsx
packages/core/src/skeleton/skeleton.tsx
packages/tailwindcss/src/index.ts

This PR introduces the Skeleton component ported from the [Mantine implementation](https://mantine.dev/core/skeleton/) with the following features:
- Ability to set whether the skeleton is visible or not. This sets a data attribute and it is up to the user to set the styles when the skeleton isn't visible.
- Ability to set whether the skeleton should animate. This sets a data attribute and it is up to the user to set the styles for when the skeleton is animatable.
- `Width`, `Height`, and `Radius` props to set the width, height, and border-radius of the skeleton in `px`.
- `Circle` prop for making the skeleton a circle using the height provided.
Some possible changes:
- Add a default animation
- Rename attributes

Feat: Add Skeleton Component

---

packages/core/src/slider/slider-context.tsx
packages/core/src/slider/slider-root.tsx
packages/core/src/slider/slider-thumb.tsx
packages/core/src/slider/slider-track.tsx

Fixed issue with thumbs moving too fast which was caused by the `Track` receiving pointer events. Fixed by adding `stopPropagation`. 
Fixed issue with the wrong thumb being selected when thumb values are 0 and they overlap.
Changed `onSlideStart` to take in an index and a value. Thumbs pass in their own index and track will use `getClosestValueIndex` method to calculate the thumb that needs to be moved.

fix(slider): fix bugs with thumb

---

apps/docs/src/examples/slider.tsx
packages/core/src/slider/create-slider-state.ts
packages/core/src/slider/slider-input.tsx
packages/core/src/slider/slider-root.tsx
packages/core/src/slider/utils.ts

Fixed the following issues with the [`Slider`](https://kobalte.dev/docs/core/components/slider):
* When using  `Home/End/PageDown/PageUp` keys, the page would scroll instead of staying in place and updating the slider values. This is not the intended behavior, so the default event is prevented and the propagation is stopped to fix it. This was reused in many places across the slider, so I abstracted it into a `util` called `stopEventDefaultAndPropagation` (feel free to ask me to bring back the old behavior with less function calls).
* Slider behavior wasn't aligned with the WAI-ARIA Multi-Thumb slider: When you have a [Multi-Thumb Slider](https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/examples/slider-multithumb/) and you press the `Home/End` key, the expectation is for the …

fix(slider): fix `Home/End/PageDown/PageUp` keys

---

packages/core/src/checkbox/checkbox-input.tsx
packages/core/src/radio-group/radio-group-item-input.tsx

Fix #291 
Based on `hidden-select-base` component handling of input events. This fix should help with uses with form libraries like `modular-forms` as discussed in #291

fix: inputs for checkbox and radiogroup to trigger change event

---

packages/core/src/context-menu/context-menu-trigger.tsx

This allows nested context menus - div with context menu containing another div with different context menu.

fix: stop propagation in context menu trigger

---

CONTRIBUTING.md
package.json
pnpm-lock.yaml

Part of #318 
Remove git hooks as they slow down and sometime break development, or just don't work on some systems.
To remove hooks installed from earlier versions:
1. Delete folder `.git/hooks/`
2. Run `git config --unset core.hooksPath`

build: remove git hooks

---

CONTRIBUTING.md
packages/core/src/context-menu/context-menu-trigger.tsx

Long pressing the menu context trigger was not positioning the context menu on iOS devices.
The PR adds a context.setAnchorRect call on pointer down event listener to position the context menu on iOS devices.
fix #271

fix(context-menu): add context.setAnchorRect call on pointer down

---

apps/docs/src/examples/toggle-group.module.css
apps/docs/src/examples/toggle-group.tsx
apps/docs/src/routes/docs/core.tsx
apps/docs/src/routes/docs/core/components/toggle-group.mdx
packages/core/src/index.tsx
packages/core/src/toggle-group/index.ts
packages/core/src/toggle-group/toggle-group-base.tsx
packages/core/src/toggle-group/toggle-group-context.tsx
packages/core/src/toggle-group/toggle-group-item.tsx
packages/core/src/toggle-group/toggle-group-root.tsx
packages/core/src/toggle-group/toggle-group.test.tsx

feat: `Toggle Group` component

---

packages/core/src/number-field/number-field-root.tsx

The new `NumberField` component is awesome, but while using it with `style: unit` format options specified, I realized it's behavior diverges pretty significantly from the lovely behavior in in the react spectrum component it's based on. This PR brings it closer into line, though it's still not quite perfect.
To see the issue:
- create a NumberField
- specify the following format options:
- attempt to type into the field:
-  a decimal number into the field
- typos like alphabetical characters
- anything into the unit segment
```typescript
const formatOptions = {
minimumFractionDigits: 0,
maximumFractionDigits: 1,
style: "unit",
unit: "second",
unitDisplay: "long"
};
```
Expected behavior:  The NumberField should normalize the user's input into a valid format
Actual behavior: The displayed …

Improve number fields behavior when formatted with a unit

---

packages/core/src/combobox/combobox-base.tsx

fix(combobox): close on select with `focus` trigger mode

---

packages/core/src/slider/create-slider-state.ts

fix(slider): call `onChangeEnd` on blur after changing value

---

packages/core/src/polymorphic/polymorphic.tsx

It took me a while to find the culprit of why my component wasn't working and it was as simple as my "component" prop overriding the component prop passed to SolidJS' Dynamic component.
Either this, or we should pass the Dynamic component's props as the Polymorphic props in TypeScript.

Update Polymorphic to override the "component" prop of Dynamic

---

packages/core/src/combobox/combobox-base.tsx

From the Combobox docs:
> optionTextValue: The property name to use as the text value of an option for filtering and keyboard navigation.
Currently `optionLabel` is used for filtering instead of `optionTextValue`. This PR changes `filterFn` to use `optionTextValue` for filtering.

Use optionTextValue in filtering

---

packages/core/package.json
packages/core/src/tabs/tabs-indicator.tsx
pnpm-lock.yaml

The tab indicator currently doesn't resize if the tab trigger changes size. Adding a resize observer on the selected tab seems to be an easy fix.
https://github.com/user-attachments/assets/f3670102-3947-4fa1-9ed9-d0701c7a7e1b
https://github.com/user-attachments/assets/d9036b4d-4cfa-4fdc-9319-1e155e9afe60

Recalculate tab indicator styles on resize

---

.changeset/nine-starfishes-join.md
packages/core/package.json
packages/core/src/pagination/pagination-items.tsx
packages/core/src/pagination/pagination-root.tsx

Added a fix for the case when paginations has fixedItems and the count is "small" which lead to
negative previousSibling pages
higher nextSibling pages than count
Added to render the pages directly if there's no need to render an ellipsis, because it would only replace one page.
All test still pass.
Side note: I converted the signals and createEffect to a single createMemo to avoid endless update loops.
Ryan Carniato once said in one of his talks that you should never set a signal from within createEffect and that it usually can be converted to a computed value (createMemo, createComputed,...) instead.
Feel free to reach out and discuss.
Spent a whole day, to figure it out. In the end it was so simple 😅
Closes: [Issue 461](https://github.com/kobaltedev/kobalte/issues/461)

Fix fixed items pagination

---

packages/core/src/combobox/combobox-base.tsx

Updates the combobox component to prevent opening the menu if the triggerMode has been set to manual, and the trigger source is not manual.
Other triggerModes are unaffected.
closes #462

bug(combobox) prevent combobox opening for input when triggerMode set to 'manual' (#462)

---

packages/core/dev/App.tsx
packages/core/package.json
packages/core/src/tooltip/tooltip-root.tsx

feat(tooltip): add skipDelayDuration prop

---

apps/docs/app.config.ts
biome.json
packages/core/src/combobox/combobox-base.tsx
packages/core/src/combobox/combobox-content.tsx
packages/core/src/combobox/combobox-input.tsx
packages/core/src/combobox/combobox-root.tsx
packages/core/src/menu/menu-content-base.tsx
packages/core/src/menu/menu-context.tsx
packages/core/src/navigation-menu/navigation-menu-root.tsx
packages/core/src/navigation-menu/navigation-menu-trigger.tsx
packages/core/src/navigation-menu/navigation-menu-viewport.tsx
packages/core/src/number-field/number-field-input.tsx
packages/core/src/number-field/number-field-root.tsx
packages/core/src/select/select-root.tsx
packages/core/src/skeleton/skeleton-root.tsx
packages/core/src/text-field/text-field-root.tsx

fixes #425 
fixes #412 
fixes #413
fixes #438 
fixes #453 
fixes #454 
fixes #431

fix: various bug fixes

---

.changeset/four-doors-sell.md
apps/docs/src/VERSIONS.ts
apps/docs/src/routes/docs/changelog/0-13-x.mdx

Update missing export from `@kobalte/utils`.
fixes #476

chore: prepare release `0.13.6`

---

packages/core/src/toggle-group/toggle-group-root.tsx

The value is possibly `null`, as the "no value" in the [implementation](https://github.com/ryoid/kobalte/blob/85f5bdc436c6a46ea81698ea098ff3fdfb9093cb/packages/core/src/toggle-group/toggle-group-root.tsx#L98-L99). This fixes the option to represent this behavior.

fix: toggle group root options

---

apps/docs/src/examples/meter.module.css
apps/docs/src/examples/meter.tsx
apps/docs/src/routes/docs/core.tsx
apps/docs/src/routes/docs/core/components/meter.mdx
packages/core/src/index.tsx
packages/core/src/meter/index.tsx
packages/core/src/meter/meter-context.tsx
packages/core/src/meter/meter-fill.tsx
packages/core/src/meter/meter-label.tsx
packages/core/src/meter/meter-root.tsx
packages/core/src/meter/meter-track.tsx
packages/core/src/meter/meter-value-label.tsx
packages/core/src/meter/meter.test.tsx
packages/core/src/progress/progress-context.tsx
packages/core/src/progress/progress-fill.tsx
packages/core/src/progress/progress-label.tsx
packages/core/src/progress/progress-root.tsx
packages/core/src/progress/progress-track.tsx
packages/core/src/progress/progress-value-label.tsx

closes #316 
- The Meter component is built on the same foundation as the Progress, sharing much of the same structure and logic.
- Key differences between the Meter and Progress bar components:
- The Meter component will always display a determinate value.
- Unlike the Progress, the Meter does not have loading or complete states, as it only reflects a specific, static value.

feat: new Meter component

---

apps/docs/src/examples/meter.tsx

Fixed typo in Meter example:
`Batter` → `Battery` (missing "y")

docs: fix a typo in Meter example

---

packages/core/src/menu/menu-radio-group-context.tsx
packages/core/src/menu/menu-radio-group.tsx
packages/core/src/menu/menu-radio-item.tsx

Fixes #574
Adds a generic parameter `TValue` to `MenuRadioGroup` and `MenuRadioItem` which allows the use of other types (not just strings) as the value for the Radio Group and Radio Items in a Dropdown Menu

feat(dropdown-menu): Generic Radio Group Values

---

packages/core/src/toggle-group/toggle-group-item.tsx

Fixes #594 by passing a function to the toggle-group-item `createSelectableItem` field.

fix: Make toggle-group-item disabled state reactive

---

packages/core/src/color-channel-field/color-channel-field-root.tsx
packages/core/src/colors/utils.ts

Fixes #589 
I refactored the `onRawValueChange` function for the `ColorChannelFieldRoot` component to be able to handle the values for the Alpha channel (Or any channel that would be in a range with fraction digits).
The first notable change I did was to de-inline the logic here that was quite difficult to read. I decomposed it by steps and applied early return pattern for the 'NaN edgecase'. But I know some people prefer conciseness, so please let me know if it would be preferred inlined it as it was.
I also used the `clamp` function from `@kobalte/utils` for the sake of DRY and clarity.
Now onto the main issue, I added the classic "multiply-round-divide" trick to be able to have values with fraction digits as is required for the alpha channel values. Instead of adding a special …

fix(color-channel-field): fix handling of alpha values

---

packages/core/src/colors/utils.test.ts
packages/core/src/colors/utils.ts

By default, commas are not needed in the color notation for **rgb**. You can also directly pass the alpha channel value in the notation. 
Also, in the future, it is worth considering the possibility of removing the **rgba** format
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb
In fact this also applies to hsl https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl

fix(colors): format color
